CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  senha VARCHAR(255) NOT NULL,
  profile_pic_url VARCHAR(255) DEFAULT NULL,
  last_login TIMESTAMP NULL,
  descricao TEXT,
  links_sociais TEXT
);
